course_advanced_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: placeholder
      user: placeholder
      password: placeholder
      role: transformer
      database: dev
      warehouse: transforming
      # Add Snowflake username below again, keep dbt_ prefix
      schema: placeholder
      # Note this thread number, we'll come back to this later in the course
      threads: 4